server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy hacia el backend
    location /api/ {
        # Usamos el nombre del servicio que definimos arriba
        proxy_pass http://backend-service:3001; 
    }
}