apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: tienda-perritos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD
        - name: MYSQL_DATABASE
          value: "tienda_perritos"
        ports:
        - containerPort: 3306
        # --- ESTO INYECTA LOS PERRITOS AUTOMÁTICAMENTE ---
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
      - name: init-script
        configMap:
          name: mysql-init
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: tienda-perritos
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - port: 3306
      targetPort: 3306