apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: tienda-perritos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 510074691011.dkr.ecr.us-east-1.amazonaws.com/tienda-frontend
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: tienda-perritos
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80