name: Deploy Fullstack to EKS

on:
  push:
    branches: [ "deploy" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Autenticar en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Construir y subir imágenes a ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # 1. Base de Datos
          docker build -t $ECR_REGISTRY/tienda-db:latest ./db
          docker push $ECR_REGISTRY/tienda-db:latest
          
          # 2. Backend
          docker build -t $ECR_REGISTRY/tienda-backend:latest ./backend
          docker push $ECR_REGISTRY/tienda-backend:latest
          
          # 3. Frontend
          docker build -t $ECR_REGISTRY/tienda-frontend:latest ./frontend
          docker push $ECR_REGISTRY/tienda-frontend:latest

      - name: Actualizar contexto de Kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name TP-cluster

      - name: Desplegar en Kubernetes
        run: |
          kubectl create namespace tienda-perritos || echo "El namespace ya existe"
          kubectl apply -f k8s/